// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "animategifimage.h"

/////////////////////////////////////////////////////////////////////////////
// CAnimateGifImage

IMPLEMENT_DYNCREATE(CAnimateGifImage, CWnd)

/////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////


long CAnimateGifImage::SetBevelWidth(const VARIANT& nBevelWidth)
{
	long result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		&nBevelWidth);
	return result;
}

long CAnimateGifImage::SetBevelStyle(const VARIANT& varBevelStyle)
{
	long result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		&varBevelStyle);
	return result;
}

long CAnimateGifImage::SetDrawBorder(const VARIANT& varbDrawBorder)
{
	long result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		&varbDrawBorder);
	return result;
}

long CAnimateGifImage::SetGifImageFilePath(LPCTSTR bstrFilePath)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		bstrFilePath);
	return result;
}

long CAnimateGifImage::SetAnimateGifImageTime(const VARIANT& varTime)
{
	long result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		&varTime);
	return result;
}

long CAnimateGifImage::AnimateGifImagePlay(LPCTSTR bstrPass)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		bstrPass);
	return result;
}

long CAnimateGifImage::AnimateGifImagePlayStop()
{
	long result;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}
