#if !defined(AFX_PICTURE_H__0C1E7D86_AB94_11D2_91E0_0080C8E1242B__INCLUDED_)
#define AFX_PICTURE_H__0C1E7D86_AB94_11D2_91E0_0080C8E1242B__INCLUDED_
// by ÓáÃ÷Â¼
#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


class CPicture : public COleDispatchDriver
{
public:
	CPicture() {}	
	CPicture(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPicture(const CPicture& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}


public:
	long GetHandle();
	long GetHPal();
	void SetHPal(long);
	short GetType();
	long GetWidth();
	long GetHeight();


public:

};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PICTURE_H__0C1E7D86_AB94_11D2_91E0_0080C8E1242B__INCLUDED_)
