#if !defined(AFX_PICTURE2_H__13415B84_7102_11D3_88F5_0080C8E20736__INCLUDED_)
#define AFX_PICTURE2_H__13415B84_7102_11D3_88F5_0080C8E20736__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


class CPicture1 : public COleDispatchDriver
{
public:
	CPicture1() {}	
	CPicture1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPicture1(const CPicture1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}


public:
	long GetHandle();
	long GetHPal();
	void SetHPal(long);
	short GetType();
	long GetWidth();
	long GetHeight();


public:

};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PICTURE2_H__13415B84_7102_11D3_88F5_0080C8E20736__INCLUDED_)
