//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TaiShan.rc
//
#define IDD_6_TJXG_ALARM                2
#define IDD_TJXG_ALARM_SET              2
#define IDC_CJQKDEL                     3
#define ID_READ                         3
#define IDC_READ                        3
#define IDCANCEL2                       3
#define IDCHOOSESTOCK                   3
#define IDC_CJQKMOD                     4
#define IDC_BUTTON_DESTINATION          4
#define ID_MODIFYZB                     4
#define IDC_MODIFYGS                    4
#define IDC_OFTEN                       4
#define IDC_CHANGEDAY                   4
#define ID_SJLL2                        5
#define ID_DELETEZB                     5
#define ID_DELETEGS                     5
#define IDD_ABOUTBOX                    100
#define IDS_BACK                        101
#define IDS_CHOOSE                      101
#define IDD_FORMVIEW                    101
#define ID_GO_BACK                      102
#define IDS_QUOTATION                   102
#define IDD_DOWNLOAD_DIALOG             102
#define IDD_DIALOGBAR                   103
#define ID_GO_FORWARD                   103
#define IDS_KLINE                       103
#define IDS_ZIBIAO                      104
#define IDS_DATA_INFO                   105
#define IDD_TIMESETDLG                  105
#define IDC_DATESTART                   105
#define IDS_INDICATE                    106
#define IDS_GONGGAO                     106
#define IDC_DATEEND                     106
#define IDS_SELECT                      107
#define IDS_DRAW                        108
#define IDS_TEST                        109
#define IDS_KLINEINDICATE               109
#define IDS_BUYSELL                     110
#define IDS_COMPANY                     111
#define IDS_HELP                        112
#define IDS_POWER                       113
#define CG_IDR_POPUP_MY_TREE_VIEW       114
#define IDR_TREE_VIEW2                  114
#define IDC_DATETIME_1                  115
#define IDC_DATETIME_2                  116
#define IDM_Index__OFTEN_1              117
#define ID_ALARM                        118
#define IDS_ALARM                       118
#define IDS_BIG_LIST                    119
#define IDS_ETERINTERNET                120
#define IDS_SJGL                        121
#define IDR_COPYTOCLIP                  122
#define IDR_COPYDAATA1                  122
#define IDS_SCREEN                      123
#define IDS_GRID                        124
#define ID_DELETE_TJXGTYPES             126
#define ID_F6                           127
#define IDR_MAINFRAME                   128
#define IDC_RICHEDIT_PINGCE             128
#define IDR_WSSTOCTYPE                  129
#define IDD_SELECT_DAYLINE              129
#define IDR_STOCK_TYPE9                 129
#define IDR_STOCTYPE                    129
#define IDD_DIALOG_PROGRESS             130
#define IDR_NEWTYPE                     130
#define IDR_VWBASETYPE                  130
#define IDR_I2                          130
#define IDR_BASE_VTYPE                  130
#define IDD_DIALOG1                     131
#define IDR_MAINFRAME2                  131
#define IDR_DRAWLINE                    131
#define IDR_VWBASETYPE3                 131
#define IDR_LINETOOL                    131
#define IDR_BOTTOMPAGE                  132
#define IDR_VWBASETYPE2                 132
#define ID_BARGAIN_SH                   133
#define IDB_TOOLBAR                     133
#define IDR_STOCKTYPE                   133
#define IDD_IMPORTDATA                  133
#define IDD_DATAIMPORT                  133
#define IDR_MENU_DISPLAY                134
#define IDB_PALETTE                     134
#define ID_BARGAIN_SZ                   134
#define IDR_MDISPLAY                    134
#define IDD_SHEETWG                     135
#define ID_REDGREEN_SH                  135
#define IDB_HOTTOOLBAR                  135
#define IDB_TOOLBAR_HOT                 135
#define IDD_SHEETZX                     136
#define ID_REDGREEN_SZ                  136
#define IDD_SHEETBK                     137
#define ID_DATE                         137
#define IDB_SMALLBITMAP                 137
#define IDD_CLEARDATA                   137
#define IDD_CLEAR_DATA                  137
#define IDD_SHEETQT                     138
#define ID_TEMP                         138
#define IDR_BASEINFO                    138
#define IDR_I1                          138
#define IDB_BITMAP7                     139
#define ID_KIND                         139
#define IDD_CUOHEDIALOG                 139
#define IDD_SHEETXGFL                   140
#define IDR_CUOHEDIALOG                 140
#define IDB_BITMAP2                     141
#define IDD_SHEETXGBK                   142
#define IDR_NOMALSCREEN                 142
#define IDB_BITMAP3                     143
#define IDD_DIATJXGDETAIL               143
#define IDB_BITMAP4                     144
#define IDB_BITMAP5                     145
#define IDD_KLINE                       145
#define IDD_DIALOGXZZB                  146
#define IDC_REDARROW                    147
#define IDR_TOOLBAR2                    147
#define IDR_NORMALSCREEN                147
#define IDC_CURSOR_SPLIT                148
#define IDD_DIALOG4                     148
#define IDD_CLEARIRRATIONALDATA         148
#define IDC_CURSOR_6                    148
#define IDC_CURSOR_MOVE                 149
#define IDC_CURSOR_3                    149
#define IDD_CORPINFO                    150
#define IDI_EXIT16                      150
#define IDD_DIALOG_KEYB                 151
#define IDB_BITMAP6                     152
#define IDD_DIALOG5                     152
#define IDB_L_BITMAP_TJXG_B             153
#define IDD_DIALOG_BASE_INFO            153
#define IDB_40                          153
#define IDB_L_BITMAP_TJXG_S             154
#define IDD_OUTPUTEXCELL                154
#define IDB_41                          154
#define IDR_POPKLINE                    155
#define IDD_SHEETXGZX                   155
#define IDR_KLINE                       155
#define IDR_WSSTOCKTYPE                 156
#define IDR_TIMESET                     156
#define IDD_DIALOG_INDEX_CHANGE_PARA    156
#define IDD_DIALOG_CHANGE_PARA          156
#define IDR_SETTIME2                    156
#define IDR_MENU_DISPLAY1               157
#define IDD_STOCKDETAIL                 157
#define IDC_CURSOR_ADD                  158
#define IDD_DIATJXG_EXPLAIN             158
#define IDC_CURSOR_SUB                  159
#define IDD_ZJTC                        159
#define IDC_CURSOR_7                    159
#define IDC_CURSOR_INFO                 160
#define IDD_DIAGSGL                     160
#define IDD_DIA_GSCC                    160
#define IDC_CURSOR_2                    160
#define IDC_MOVE_BODY                   161
#define IDB_BIGBITMAP                   161
#define IDD_SJGL                        161
#define IDD_MANAGEDATA                  161
#define IDC_MOVE_8                      161
#define IDC_MOVE_POINT                  162
#define IDD_EDITZBCS                    162
#define IDD_EDIT_ZBGS                   162
#define IDC_CURSOR_8                    162
#define IDD_EDITZJXT                    163
#define IDB_UP_BUY                      164
#define IDD_EDITTJXG                    164
#define IDD_EDIT_TJXGGS                 164
#define IDB_70                          164
#define IDB_DOWN_SELL                   165
#define IDD_DQSUZL                      165
#define IDD_DATARESTORE                 165
#define IDB_30                          165
#define IDD_SHOW_TEXT                   166
#define IDR_TOOLBAR1                    167
#define IDD_LSSJGL                      167
#define IDB_BITMAP1                     168
#define IDD_DMDZ                        168
#define IDB_BITMAP21                    168
#define IDB_COLDTOOLBAR                 169
#define IDR_MENU_BLOCK                  169
#define IDR_BLOCKM                      169
#define ID_CURSOR_MULTI                 170
#define IDD_DIATJXG                     170
#define ID_CURSOR_9                     170
#define IDD_DIALOG_SHIDUAN_TJ           171
#define IDD_DIALOG2                     172
#define IDD_DIALOG_K_CHANGE_L           172
#define IDD_DIALOG_CHANGE1              172
#define IDD_DIALOGMAINFRAME             173
#define IDD_SHEETTZGLCJ                 174
#define IDD_SHEETTZGLZJ                 175
#define IDB_BITMAP_KLINE_MODE           175
#define IDB_BITMAP_137                  175
#define IDD_DIATZGLCJSR                 176
#define IDB_BITMAP_BASE_INFO            176
#define IDB_BITMAP_136                  176
#define IDD_DIATZGLLJXQ                 177
#define IDB_BITMAP_POWER                177
#define IDB_BITMAP_138                  177
#define IDD_HqDetailDIALOG              178
#define IDD_SHEETBKSWCY                 179
#define IDD_SHEETBKADD                  180
#define IDB_DISABLEBAR                  180
#define IDD_SHEETBKSET                  181
#define IDD_OUTPUT2EXCEL                182
#define IDD_EDITZBGSHS                  183
#define IDD_EDIT_HS                     183
#define IDD_DIAGSGLMM                   184
#define IDD_KEYBRODEANGEL               185
#define IDD_ANGELKEYBRODE               185
#define IDD_SHEETZX1                    186
#define IDD_REORGANIZEDAYLINEDATA       186
#define IDD_SHEETXGFL1                  187
#define IDD_DIACOPY                     187
#define IDD_SHEETXGBK1                  188
#define IDB_BITMAP8                     188
#define IDD_SHEETWG1                    189
#define IDD_SHEETQT1                    190
#define IDD_SHEETBK1                    191
#define IDB_BITMAP9                     191
#define IDD_DIATZGLDL                   192
#define IDB_BITMAP10                    192
#define IDD_DIATZGLADD                  193
#define IDD_DIATJXGZS                   194
#define IDD_DIALOGMAINFRAME1            195
#define IDD_DIALOG_MODCJMX              196
#define IDD_DIALOG_ADDCHUAN             197
#define IDD_DIALOGCHUQUAN               197
#define IDD_DIALOG3                     198
#define IDD_ABOUTBOX1                   199
#define IDD_DIALOGZLLBNEW               200
#define IDD_DIALOGZLLB                  201
#define IDI_ICON1                       201
#define IDD_DIALOGGSSM                  202
#define IDD_DIALOGGSZS                  202
#define IDD_DIALOG_MODCJMX1             203
#define IDD_DIALOG_KLINE_MODE           204
#define IDB_START                       204
#define IDD_DIALOG_KLINE_M              204
#define IDD_DIALOG_SHIDUAN_TJ1          205
#define IDD_DIATJXGRESULT               206
#define IDR_MYTREETYPE                  206
#define IDD_OUTINPOWER                  207
#define IDR_F10TYPE                     207
#define IDR_COMPANYINFO2                207
#define IDD_STOCK_SELECT                208
#define IDD_SHEETBKNEWNAME              209
#define IDD_MODIFYPASSWORD              210
#define IDI_ICON2                       210
#define IDD_SERIAL                      211
#define IDI_ICON3                       211
#define IDD_DIALOGTEST                  212
#define IDD_FY_REGISTER                 213
#define IDD_FY_ADDMONEY                 214
#define IDB_BITMAP11                    217
#define IDI_ICON4                       218
#define IDD_COLUMN_SELECT               219
#define IDD_STOCKINFOINPUT              220
#define IDD_SharesSymbol_INPUT          220
#define IDD_LMB_CLASSIFY_JISHU          221
#define IDC_CURSOR_DRAG                 222
#define IDD_LMB_SET_JISHU_NAME          222
#define IDD_SET_JISHU_NAME              222
#define IDC_CURSOR_1                    222
#define IDD_GETUPDATEFILE               223
#define IDD_UPDATEFILE                  223
#define IDD_DIALOG_MODCJMX2             224
#define IDC_CURSOR_DISABLE              224
#define IDD_SYSSETLH                    224
#define IDD_PARA                        224
#define IDD_SET_PARAM                   224
#define IDC_CURSOR_MOVE_L               225
#define IDC_CURSOR_4                    225
#define IDD_LMB_DEAL_HISTORY            226
#define IDD_DEAL_HISTORY                226
#define IDC_CURSOR_COPY                 227
#define IDD_LMB_HISTORY_SELECT          227
#define IDD_HISTORY_SELECT              227
#define IDC_CURSOR_5                    227
#define IDB_L_DEAL_HISTORY              228
#define IDB_51                          228
#define IDD_DIALOG_SETMAXMIN_L          229
#define IDB_L_DEAL_HISTORY_DIS          229
#define IDB_52                          229
#define IDD_5_TJXG_PARENT               230
#define IDD_PARENT_TJXG                 230
#define IDD_sort_index                  231
#define IDD_INDEXSORT                   231
#define IDD_TJXGNEW                     232
#define IDD_SHOWTJXG                    232
#define IDB_BITMAP12                    234
#define IDB_BITMAP13                    235
#define IDB_BITMAP14                    236
#define IDB_BITMAP15                    237
#define IDD_CALC                        240
#define IDD_COMPUTEINDEX                240
#define IDD_DIALOG6                     241
#define IDR_COPYTO_GRID                 242
#define IDD_TJXG_ALARM                  243
#define IDD_SETUP_PARAM                 245
#define IDD_SET2_PARAM                  245
#define IDD_DIALOG7                     246
#define IDD_STOCKTYPE                   246
#define IDD_TYPE_STOCK                  246
#define IDD_DIALOG8                     247
#define IDD_MANAGER_STOCKTYPE           248
#define IDD_6_TJXG_TEST                 249
#define IDD_6_STOP_LOSE                 251
#define IDD_STOP_LOSE_CASE              251
#define IDD_6_CHANGE_PARAM              254
#define IDD_6_TJXG_INDICATE             255
#define IDD_6_TRADE_DETAIL_SET          257
#define IDD_6_MANAGE_LJISHU             259
#define IDD_MANAGE_GONGSHI              259
#define IDD_6_EDIT_TJXG_KMODE           260
#define IDD_EDIT_TJXG_K                 260
#define IDD_6_NEURAL_TRAIN              263
#define IDD_MODIFY_STOCKTYPE            264
#define IDD_MANAGER_CHOOSE              265
#define IDD_CHOOSE_MANAGER              265
#define IDD_7_ALARM_ADDED_CASE          266
#define IDD_ALARM_ADDED_CASE            266
#define IDB_BITMAP16                    269
#define IDB_ALARMGRAY                   270
#define IDB_ALARM                       271
#define IDB_STATUSBAR_INDICATOR         273
#define IDB_60                          273
#define IDD_7_NNET_TRAIN                274
#define IDD_7_TRADE_DETAIL_RESULT       275
#define IDB_BITMAP17                    277
#define IDB_EVERY                       278
#define IDB_BMP_MENU                    279
#define IDD_8_OUT_DATA                  281
#define IDD_OUT_DATA                    281
#define IDD_8_ADD_KLINE_SELF            283
#define IDD_ADD_KLINE_SELF              283
#define IDD_SYMBOLCONTRAST              284
#define IDD_CONTRAST_SYMBOL             284
#define IDD_MANAGEINVEST                285
#define IDD_EXPORTDATA                  286
#define IDD_DATAEXPOR                   286
#define IDD_8_ALARM_SYSTEM              287
#define IDD_MYALERT_SYSTEM              287
#define IDD_8_POP_ALARM                 288
#define IDD_1UPALERT                    288
#define IDD_8_CAN_USED                  289
#define IDD_CAN_USED                    289
#define IDD_EDITINVEST                  291
#define IDC_CURSOR1                     291
#define IDD_EDIT_INV2                   291
#define IDD_TRANSACTFEE                 292
#define IDD_TRANSACT_RATE               292
#define IDD_8_PARAM_EXPLAIN             293
#define IDD_INVESTLOGIN                 294
#define IDD_EDITACCOUNT                 295
#define IDB_DIAL                        304
#define IDB_ACCOUNT                     306
#define IDI_CARD                        308
#define IDD_RISKINDEX                   310
#define IDD_9_INDICATOR_OFTEN           311
#define IDD_CAIWUDATA                   315
#define IDD_CAIWUINOUT                  315
#define IDD_CHUQUANDATA                 316
#define IDD_POWER2                      316
#define IDB_BIGBITMAP2                  317
#define IDB_BIGBITMAP2_NET              317
#define IDB_DISABLEBAR2                 318
#define IDB_DISABLEBAR2_NET             318
#define IDD_SYSPARAME                   319
#define IDD_SYSWG                       320
#define IDD_WG2_SYSTEMINFO              320
#define IDD_SYSSZ                       321
#define IDD_SZ_SYSTEMINFO               321
#define IDI_ACCOUNT                     322
#define IDI_ACCOUNT1                    322
#define IDB_BITMAP_11_BELL              329
#define IDB_BITMAP_135                  329
#define IDB_BITMAP_11_ALARMRESULT       330
#define IDR_STATUS                      330
#define IDB_BITMAP_113                  330
#define IDB_BITMAP_11_BELL2             331
#define IDD_REALTIME_DETAIL             331
#define IDD_DETAIL_HS                   331
#define IDB_BITMAP_11_BELL3             332
#define IDD_STOCK_REALTIME_DETAIL       332
#define IDD_DETAIL_STOCK                332
#define IDB_BITMAP_11_BELL4             333
#define IDB_BITMAP_11_BELL5             334
#define IDB_BITMAP_11_BELL6             335
#define IDD_11_EDIT_DATA                335
#define IDB_BITMAP_11_BELL7             336
#define IDB_BITMAP_11_BELL8             337
#define IDB_BITMAP_11_BELL9             338
#define IDB_BITMAP_11_ALARMCOND         339
#define IDB_BITMAP_110                  339
#define IDB_BITMAP_11_ALARMPRICE        340
#define IDB_BITMAP_112                  340
#define IDB_BITMAP_11_ALARMUPDOWN       341
#define IDB_BITMAP_114                  341
#define IDB_BITMAP_11_ALARMVOL          342
#define IDB_BITMAP_131                  342
#define IDB_BITMAP_11_ALARMLINE         343
#define IDB_BITMAP_111                  343
#define IDB_BITMAP_11_INDICATOR_GROUP   344
#define IDB_BITMAP_132                  344
#define IDB_BITMAP_11_INDICATOR_KIND    345
#define IDB_BITMAP_133                  345
#define IDB_BITMAP_11_SCREEN_BASE       346
#define IDB_BITMAP_134                  346
#define IDB_BITMAP_11_BELL18            347
#define IDB_BITMAP_11_BELL19            348
#define IDB_BITMAP_11_BELL20            349
#define IDI_ICON5                       352
#define IDD_DIALOG9                     362
#define IDD_RECV_STOCKCODE              362
#define IDD_DIALOG10                    363
#define IDR_NINE_VIEW                   364
#define IDR_MENU1                       364
#define IDD_DIALOG_PROGRESS_PC          366
#define IDD_STOCK_HIS_DETAIL            367
#define IDB_ADDUP                       372
#define IDB_DELUP                       373
#define IDD_DIALOG11                    374
#define IDD_STOCKTYPE1                  375
#define IDD_TYPE_STOCK1                 375
#define IDD_STOCK_HIS_DETAIL2           376
#define IDD_DIALOG_tongji_zb            378
#define IDD_200107_PARAM                379
#define IDD_MYXMZ                       380
#define IDI_MYXMZ                       382
#define IDB_MYLIST                      384
#define IDD_WIDEDOWNLOAD                385
#define IDD_DIALOG_LOGON                387
#define IDR_MAINFRAME_WIDE              388
#define IDR_VWBASETYPE_WIDE             389
#define IDB_DISTOOLBAR                  393
#define IDB_TOOLBAR_DIS                 393
#define IDD_DIALOG12                    394
#define IDI_ICON6                       395
#define IDB_1                           397
#define IDB_2                           398
#define IDD_XGN_EXTDATA_PROP            399
#define IDD_XGN_MODIFY_EXT              400
#define IDB_BITMAP18                    401
#define IDD_XGN_SEL_ID                  401
#define IDB_BITMAP19                    402
#define IDB_BITMAP20                    403
#define IDI_ICON_LAUGHT                 404
#define IDI_ICON_SAVE                   405
#define IDI_ICON_OPEN                   406
#define IDI_ICON_DELETE                 410
#define IDI_ICON_ADD                    411
#define IDI_ICON_2                      412
#define IDI_ICON_ADD2                   416
#define IDI_ICON_SUB                    417
#define IDI_ICON_SCREEN                 418
#define IDC_HAND_1                      419
#define IDB_BITMAP22                    420
#define IDI_ICON_OK                     421
#define IDB_BITMAP_leftbott             422
#define IDD_DIALOG_SELECT_DATE          422
#define IDI_ICON7_DRAWLINE              423
#define IDI_ICON7_DADAN                 424
#define IDI_ICON7_HANGQING              425
#define IDI_ICON7_OPEN                  426
#define IDI_ICON7_TEST                  427
#define IDI_ICON7_SCREEN                428
#define IDI_ICON7_XX                    429
#define IDI_ICON7_XX1                   430
#define IDI_ICON7_ZIXUN                 431
#define IDI_ICON7                       432
#define IDR_MAINFRAME_HEAD              433
#define IDD_DIALOG_SHOW_HTML            435
#define IDB_BITMAP23                    436
#define IDR_MENU_COPY_PASTE             437
#define IDD_CWD_LEFT_POP                438
#define IDD_CWD_IMPORT_FORMU            439
#define IDD_CWD_SHOW_FORMU              440
#define IDD_CWD_CLOSEWORK               441
#define IDB_BJ_CHENGBEN                 441
#define IDB_DRAWICON1                   442
#define IDD_CWD_OVERWRITE_FORMULAR      443
#define IDB_BITMAP24                    444
#define IDD_CWD_EDIT_PARAM              445
#define ID_PALETTE_BASE                 601
#define ID_PALETTEERASE                 601
#define ID_PALETTEPEN                   602
#define ID_PALETTESELECT                603
#define ID_PALETTEBRUSH                 604
#define ID_PALETTESPRAY                 605
#define ID_PALETTEPAINT                 606
#define ID_PALETTELINE                  607
#define ID_PALETTEEYEDROP               608
#define ID_PALETTEMAG                   609
#define ID_PALETTERECT                  610
#define ID_PALETTEROUND                 611
#define ID_PALETTEOVAL                  612
#define ID_BEGIN_LINE                   699
#define ID_XIAN_DUAN                    700
#define ID_SHUI_PING                    701
#define ID_QU_SHI                       702
#define ID_PING_XING                    703
#define ID_SU_DU                        704
#define ID_SHAN_XING                    705
#define ID_GAN_SHI                      706
#define ID_HUANG_JIN                    707
#define ID_BO_DUAN                      708
#define ID_BAI_FEN_BI                   709
#define ID_HUI_GUI                      710
#define ID_HUI_GUI_DAI_1                711
#define ID_HUI_GUI_DAI_2                712
#define ID_ZHOU_QI                      713
#define ID_NA_QI                        714
#define ID_ZHONG_XIAN                   715
#define ID_NA_QI_HU                     716
#define ID_HUANG_JIN_HU                 717
#define ID_UP_ARROW                     718
#define ID_DOWN_ARROW                   719
#define ID_RECT_KIND                    720
#define ID_TEXT_KIND                    721
#define ID_DELETE_LINE                  722
#define ID_BAG_LINE                     723
#define ID_SPIRE_LINE2                  724
#define ID_WAVE_LINE                    725
#define ID_OTHER_LINE                   726
#define ID_ERASE                        801
#define ID_PEN                          802
#define ID_SELECT                       803
#define ID_BRUSH                        804
#define ID_SPRAY                        805
#define ID_PAINT                        806
#define ID_LINE                         807
#define ID_EYEDROP                      808
#define ID_MAG                          809
#define ID_RECT                         810
#define ID_ROUND                        811
#define ID_OVER                         812
#define IDC_PROGRESS                    1000
#define IDC_DELETE_LOADDATA             1000
#define IDC_ZQDM                        1001
#define IDC_DOWNLOAD_START              1001
#define IDC_ZQMC                        1002
#define IDC_STOPDOWNLOAD                1002
#define IDC_COMP                        1003
#define IDC_COMBO1                      1003
#define IDC_HOWMANYTIME                 1003
#define IDC_SETUP_TIME                  1003
#define IDC_TIMESPIN                    1004
#define IDC_COMBO5                      1004
#define IDC_EDIT                        1004
#define IDC_DOWNLOAD_INFO               1004
#define ID_DAYLINE_LIST                 1004
#define IDC_LIST1                       1005
#define IDC_STATIC_TIMESTART            1005
#define IDC_FEE                         1005
#define IDC_INSTALL_LOADDATA            1005
#define IDC_BUTTON1                     1006
#define IDC_LIST3                       1006
#define IDC_BUTTON_SEARCHFIXDATA        1006
#define IDC_SYMBOLCOMPARE               1006
#define IDC_STATIC_TIMEEND              1006
#define IDC_LOAD_COLLECTE               1006
#define IDC_LISTRISKINDEX               1006
#define IDC_BUTTON2                     1007
#define IDC_STATIC_RANGE                1007
#define IDC_UPDATESTOCKTYPE             1007
#define IDC_SAVE_COLLECTE               1007
#define IDC_BUTTON5                     1008
#define IDC_SYMBOL                      1008
#define IDC_STATIC_PROFIT               1008
#define IDC_BTN_DELETE_STK              1008
#define IDC_DELETESTOCKTYPE             1008
#define IDC_PROGRESS_DOWNLOAD           1008
#define IDC_PHONETIC                    1009
#define IDC_STATIC_STOCKRATE            1009
#define IDC_STATIC_TIP                  1009
#define IDC_BUTTON6                     1009
#define IDC_LOAD                        1009
#define IDC_MSFLEXGRID1                 1010
#define IDC_SELECT_LOADDATA             1010
#define IDC_LIST2                       1011
#define IDC_DATETIMEPICKER2             1011
#define IDC_STATIC_STARTTIME            1011
#define ID_DAYLINE                      1011
#define IDC_BUTTON3                     1012
#define IDC_BLOCKDEL                    1012
#define IDC_ZEROPRICE                   1012
#define IDC_STATIC_ENDTIME              1012
#define IDC_COMBO_SELECT_INDEX          1012
#define IDC_EDIT_TM                     1012
#define IDC_COMBO3                      1012
#define IDC_SETUP                       1012
#define IDC_AGGREGATION2                1012
#define IDC_REFRESH                     1012
#define IDC_DELETE_STOCKS               1012
#define ID_MONTHLINE                    1012
#define IDC_BUTTON4                     1013
#define IDC_YRZBGS                      1013
#define IDC_EXCESSPRICE                 1013
#define IDC_STATIC_PERIOD               1013
#define IDC_BTN_ADD_CASE                1013
#define IDC_OUTPUTEXCEL                 1013
#define IDC_BUTTON_EVENT_BIG            1013
#define IDC_COMBO4                      1013
#define IDC_OPERATOR                    1013
#define IDC_MANAGERCHOOSE               1013
#define ID_YEARLINE                     1013
#define IDC_DATE                        1014
#define IDC_EDIT_N                      1014
#define IDC_RADIO_ASSIGNPERIOD          1014
#define IDC_EXPLAIN                     1014
#define IDC_STATIC99                    1014
#define IDC_AGGREGATION3                1014
#define IDC_MONTHCALENDAR1              1014
#define IDC_EDIT2                       1015
#define IDC_CHANGEPAGE                  1015
#define IDC_DETAIL                      1015
#define IDC_TABEDIT                     1015
#define IDC_CONTINUOUS                  1015
#define IDC_STATIC_CHOOSERATE           1015
#define IDC_LIST_CASE_SELECTED          1015
#define IDC_EDIT_ASSIGNDAYS             1015
#define IDC_STATIC_HLP_NAME             1015
#define IDC_SEARCH                      1015
#define IDC_SYSSET_CHANGEPAGETIME       1015
#define IDC_DELETE_STOCKS2              1015
#define IDC_EDIT_N2                     1015
#define IDC_STATIC_CREDIT               1015
#define IDC_EDIT3                       1016
#define IDC_NOTICESAVE                  1016
#define IDC_XLINE                       1016
#define IDC_CHAOS                       1016
#define IDC_BACKCOLOR                   1016
#define IDC_STATIC_STOCKCOUNT           1016
#define IDC_EDIT_LL                     1016
#define IDC_PROGRESS2                   1016
#define IDC_RADIO_RECENTDAYS            1016
#define IDC_BLOCKNAME                   1016
#define IDC_STATIC1                     1016
#define IDC_TOTALFLOAT                  1016
#define IDC_NEWPASSWORD                 1016
#define IDC_EDIT4                       1017
#define IDC_FIVEMINUTESAVE              1017
#define IDC_TITLECOLOR                  1017
#define IDC_STATIC_SUCCESSSTOCK         1017
#define IDC_BEGINCLEAR                  1017
#define IDC_EDIT_P3_P                   1017
#define IDC_STATIC_HLP_COM              1017
#define IDC_STATIC_OUTPUT               1017
#define IDC_CALC                        1017
#define IDC_STATIC_SERIAL               1017
#define IDC_EDIT5                       1018
#define IDC_EDIT21                      1018
#define IDC_STOCKNAMECOLOR              1018
#define IDC_STATIC_CHOOSECOUNT          1018
#define IDC_EDIT_LL3_P4                 1018
#define IDC_STATIC_NAME0                1018
#define IDC_STOCKNAME                   1018
#define IDC_MODIFYPASSWORD              1018
#define IDC_EDIT6                       1019
#define IDC_BUYRATE                     1019
#define IDC_EDIT31                      1019
#define IDC_PROG                        1019
#define IDC_OTHERDATACOLOR              1019
#define IDC_STATIC_SUCCESSCOUNT         1019
#define IDC_STATIC_P3                   1019
#define IDC_STATIC_NAME1                1019
#define IDC_DELETEONESTOCK              1019
#define IDC_USERNAME                    1019
#define IDC_CHOOSED_NUM                 1019
#define IDC_INSTALLSTART                1019
#define IDC_RADIO1                      1020
#define IDC_RADIOHZB                    1020
#define IDC_RADIO_COVER                 1020
#define IDC_ZTDJ                        1020
#define IDC_RADIOSH                     1020
#define IDC_RADIOBUY                    1020
#define IDC_RADIOADD                    1020
#define IDC_STOCKUPCOLOR                1020
#define IDC_RIOADD                      1020
#define IDC_RADIO_OR_SHOW               1020
#define IDC_RADIO_FIR                   1020
#define IDC_BUY                         1020
#define IDC_STATIC_NAME2                1020
#define IDC_SharesSymbol                1020
#define IDC_OLDPASSWORD                 1020
#define IDC_INSTALLEND                  1020
#define IDC_EDIT_LL2                    1020
#define IDC_EDIT17                      1020
#define IDC_RADIO2                      1021
#define IDC_RADIOMXB                    1021
#define IDC_RADIO_REPAIRE               1021
#define IDC_FT                          1021
#define IDC_RADIOSZ                     1021
#define IDC_RADIOSELL                   1021
#define IDC_RADIOOR                     1021
#define IDC_STOCKDOWNCOLOR              1021
#define IDC_RIOOR                       1021
#define IDC_RADIO_AND_SHOW              1021
#define IDC_RADIO_SEC                   1021
#define IDC_SELL                        1021
#define IDC_STATIC_NAME3                1021
#define IDC_EDIT_P3_P2                  1021
#define IDC_EDIT_INDEX                  1022
#define IDC_SETCOLOR                    1022
#define IDC_EDIT41                      1022
#define IDC_EDIT_P3                     1022
#define IDC_SETDEFAULT                  1022
#define IDC_RADIO_INSTALLDATE           1022
#define IDC_STATIC_P4                   1022
#define IDC_RADIO_END                   1022
#define IDC_STATIC_NAME4                1022
#define IDC_RADIO7                      1022
#define IDC_SCROLLBAR1                  1023
#define IDC_SETFONT                     1023
#define IDC_EDIT32                      1023
#define IDC_RADIORX2                    1023
#define IDC_EDIT_P4                     1023
#define IDC_STOCKSTOPCOLOR              1023
#define IDC_SPIN_P4                     1023
#define IDC_COMBO_OUTFILE               1023
#define IDC_STATIC_NAME5                1023
#define IDC_OUTTYPE                     1023
#define IDC_STATICYL                    1024
#define IDC_EDIT12                      1024
#define IDC_RADIO5FZX2                  1024
#define IDC_EDIT_CHENBEN                1024
#define IDC_EDIT_OPEN_CHG               1024
#define IDC_SPIN_P3                     1024
#define IDC_CURDIR                      1024
#define IDC_STATIC_NAME6                1024
#define IDC_STATIC_CUIWEI               1024
#define IDC_RADIO5                      1024
#define ID_OK                           1025
#define IDC_EDIT42                      1025
#define IDC_RADIORX3                    1025
#define IDC_EDIT_OPEN                   1025
#define IDC_EDIT_HIGH_CHG               1025
#define IDC_BUTTON_SET                  1025
#define IDC_COMBO_MARKET                1025
#define IDC_STATIC_NAME7                1025
#define IDC_REORGANIZE                  1025
#define IDC_RADIO6                      1025
#define IDC_EDIT22                      1026
#define IDC_RADIO5FZX3                  1026
#define IDC_EDIT_HIGH                   1026
#define IDC_EDIT_LOW_CHG                1026
#define IDC_BUTTON_RESTORE              1026
#define IDC_OUT                         1026
#define IDC_STATIC_NAME8                1026
#define IDC_INSTALL_START               1026
#define IDC_DTPICKER1                   1027
#define IDC_EDIT13                      1027
#define IDC_EDIT_LOW                    1027
#define IDC_IN                          1027
#define IDC_STATIC_NAME9                1027
#define IDC_INSTALL_END                 1027
#define IDC_SPIN_P5                     1027
#define IDC_ADD                         1028
#define IDC_EDIT23                      1028
#define IDC_EDIT_CLOSE                  1028
#define IDC_OUTFILE                     1028
#define IDC_PRODUCE_START               1028
#define IDC_EDIT_LL3_P5                 1028
#define IDC_DELETE                      1029
#define IDC_RISERANGE                   1029
#define IDC_EDIT33                      1029
#define IDC_MODIFY                      1029
#define IDC_EDIT_VOL                    1029
#define IDC_EDIT_CLOSE_CHG              1029
#define IDC_INFILE                      1029
#define IDC_ALARMPERCENT                1029
#define IDC_PRODUCE_END                 1029
#define IDC_SPIN_P6                     1029
#define IDC_ADD2                        1029
#define IDC_MODIFYCQ                    1030
#define IDC_COMPARERISE                 1030
#define IDC_EDIT43                      1030
#define IDC_DELETE2                     1030
#define ID_AMOUNT_TJ                    1030
#define IDC_EDIT_VOL_CHG                1030
#define IDC_ADVSPTIMES                  1030
#define IDC_STATIC_P5                   1030
#define IDC_AUTOMINUTE                  1031
#define IDC_EDIT14                      1031
#define IDC_EDIT_JUN_JIA                1031
#define IDC_EDIT_AMOUNT_CHG             1031
#define IDC_STATIC_P6                   1031
#define IDC_AUTOWEEK                    1032
#define IDC_EDIT24                      1032
#define IDC_EDIT_ZHD_FU                 1032
#define IDC_AUTODAY                     1032
#define IDC_AUTOCLOSE                   1033
#define IDC_EDIT34                      1033
#define IDC_EDIT_ZHD                    1033
#define IDC_EDIT44                      1034
#define IDC_SHOWXLINE                   1034
#define IDC_EDIT_HUANSHOU               1034
#define IDC_LATEDDATA                   1035
#define IDC_EDIT15                      1035
#define IDC_BUTTON_POWER                1035
#define IDC_SHOWYLINE                   1035
#define IDC_LISTALL                     1036
#define IDC_EDIT25                      1036
#define IDC_EDIT_TIME_NUM               1036
#define IDC_STATIC_DATE                 1036
#define IDC_EDIT_ENSUREPASSWORD         1036
#define IDC_LISTSELECT                  1037
#define IDC_EDIT35                      1037
#define IDC_STATIC_TIME1                1037
#define IDC_STATIC_STATUS               1037
#define IDC_EDIT45                      1038
#define IDC_STATIC_TIME2                1038
#define IDC_ALARM_SOUND                 1038
#define IDC_LIST_KLINE_MODE_L           1039
#define IDC_AUTO_ORGANIZEDATA           1039
#define IDC_TAB5                        1040
#define IDC_EDIT1                       1041
#define IDC_EDIT7                       1042
#define IDC_EDIT_BRIEF                  1042
#define IDC_EDIT_PROFIT_T_1             1042
#define IDC_SJLSTOCKCODE                1042
#define IDC_EDIT8                       1043
#define IDC_TAB1                        1043
#define IDC_EDIT_CONTENT_TOTAL          1043
#define IDC_SJLSTOCKPYJC                1043
#define IDC_EDIT9                       1044
#define IDC_TABLIST                     1044
#define IDC_EDIT_CONTENT_SYMBOL         1044
#define IDC_SJLSTOCKNAME                1044
#define IDC_EDITCOMMISSION              1045
#define IDC_DELETECHUQUAN               1045
#define IDC_SYSSET_CAPITALTIME          1045
#define IDC_PARAM0                      1045
#define IDC_EDIT10                      1045
#define IDC_ADDZB                       1046
#define IDC_ADDGS                       1046
#define IDC_COMMONBLOCKNAME             1046
#define IDC_SYSSET_QUANTITYTIME         1046
#define IDC_PARAM1                      1046
#define IDC_LIST5                       1046
#define IDC_EDIT16                      1046
#define ID_SAVE                         1047
#define IDC_SYSSET_SWINGTIME            1047
#define IDC_PARAM2                      1047
#define IDC_HFQS                        1048
#define IDC_SYSSET_CHANGEHANDTIME       1048
#define IDC_PARAM3                      1048
#define IDC_CSGS                        1049
#define IDC_SYSSET_POWERSELECTSTOCK     1049
#define IDC_PARAM4                      1049
#define IDC_BUTTON8                     1049
#define IDC_CLOSE1                      1049
#define IDC_INPUT                       1050
#define IDC_SYSSET_VOLPOWER             1050
#define IDC_PARAM5                      1050
#define IDC_TAB                         1050
#define IDC_DYHS                        1051
#define IDC_SYSSET_HSTODAYADDLAST       1051
#define IDC_PARAM6                      1051
#define IDC_NAME                        1052
#define IDC_SYSSET_AUTOSAVEZHIBIAO      1052
#define IDC_PARAM7                      1052
#define IDC_EDIT11                      1053
#define IDC_SYSSET_SHOWINFOCROSS        1053
#define IDC_PARAM8                      1053
#define IDC_GJXX                        1054
#define IDC_SYSSET_STARTALERT           1054
#define IDC_CRHS                        1055
#define IDC_CHECKSH                     1055
#define IDC_SYSSET_MULTIDAY             1055
#define IDC_CHECKSZ                     1056
#define IDC_SYSSET_DAYLINE              1056
#define IDC_SYSSET_FENBI                1057
#define IDC_SYSSET_FIVEMINU             1058
#define IDC_SYSSET_NOFINISHED           1059
#define IDC_SYSSET_WARNTIME             1060
#define IDC_SYSSET_BUYDEAL              1061
#define IDC_PROGRESS1                   1062
#define IDC_SYSSET_SELDEAL              1062
#define IDC_SYSSET_UPSPEEDTIME          1063
#define IDC_YFSM                        1064
#define IDC_USER_HELP                   1064
#define IDC_FORMAL_EXPLAIN              1064
#define IDC_SYSSET_MIDWAY               1064
#define IDC_COMBO2                      1065
#define IDC_CHOOSE_HELP                 1065
#define IDC_INTYPE                      1065
#define IDC_TREE_FORMULAR_ALL           1065
#define IDC_COMBO_KIND_TIME             1065
#define IDC_LIST_FORMULAR_LINE_ALL      1066
#define IDC_SCROLLBAR2                  1067
#define IDC_LIST_SUB_FORMULAR           1067
#define IDC_RADIODT                     1068
#define IDC_EDIT_PARAM1                 1068
#define IDC_RADIOKT                     1069
#define IDC_EDIT_PARAM2                 1069
#define IDC_PARAM_LIST                  1070
#define IDC_TAB3                        1071
#define IDC_TAB43                       1071
#define IDC_EDIT_PARAM3                 1071
#define IDC_IMAGELIST                   1072
#define IDC_LIST_STOCKRANGE             1072
#define IDC_JISHU                       1072
#define IDC_ADDGUEST                    1073
#define IDC_DIVIDER                     1073
#define IDC_DELGUEST                    1074
#define IDC_BUTTON7                     1074
#define IDC_EQUAL                       1074
#define IDC_EDIT_PARAM4                 1074
#define IDC_CJQKADD                     1077
#define IDC_RADIOCR                     1078
#define IDC_SORTHELP                    1078
#define IDC_RADIOQC                     1079
#define IDC_SPIN1                       1079
#define IDC_CHOOSE_LIST                 1079
#define IDC_SPIN2                       1080
#define IDC_AGGREGATION_LIST            1080
#define IDC_SPIN3                       1081
#define IDC_STOCK_LIST                  1081
#define IDC_SWCYBK                      1082
#define IDC_SPIN4                       1082
#define IDC_LISTJISHU                   1082
#define IDC_BLOCKADD                    1083
#define IDC_STATIC_P1                   1083
#define IDC_BLOCKSET                    1084
#define IDC_STATIC_P2                   1084
#define IDC_INDEX                       1085
#define IDC_CUSTOM1                     1085
#define IDC_BKNAME                      1086
#define IDC_CHECK1                      1086
#define IDC_BKTOTALSTOCK                1087
#define IDC_CHECK2                      1087
#define IDC_STOCK_NUMBER                1087
#define IDC_BKCHOOSE                    1088
#define IDC_CHECK3                      1088
#define IDC_SELECTED_NUMBER             1088
#define IDD_BUTTON_BEGINFIX             1089
#define IDC_CHECK4                      1089
#define ID_BUTTON_BEGINPRODUCE          1090
#define IDC_START                       1090
#define IDC_SAVE_LIST                   1091
#define IDC_AGGREGATION1                1092
#define IDC_RADIO_AND                   1093
#define IDC_RADIO_OR                    1094
#define IDC_AND                         1095
#define IDC_RADIO3                      1096
#define IDC_OR                          1096
#define IDC_CHECK5                      1096
#define IDC_RADIO4                      1097
#define IDC_CHECK6                      1097
#define IDC_RADIO4T                     1098
#define IDC_DISPLAYSET                  1098
#define IDC_RADIO9T                     1099
#define IDC_DISPLAYTJ                   1099
#define IDC_DEL                         1100
#define IDC_TJDISP                      1100
#define IDC_COMBO_DATATYPE              1101
#define IDC_SAVE                        1101
#define IDC_BIG1                        1101
#define IDC_EDIT_DATASOURCE             1102
#define IDC_BRIEFEXPLAIN                1102
#define IDC_OPEN                        1102
#define IDC_BIG2                        1102
#define IDC_EDIT_FIXSTARTDATE           1103
#define IDC_CHECKMM                     1103
#define IDC_BIG3                        1103
#define IDC_EDIT_FIXENDDATE             1104
#define IDC_BIG4                        1104
#define IDC_CHECK_SZ                    1105
#define IDC_TREE1                       1105
#define IDC_DW                          1105
#define IDC_CHECK_SH                    1106
#define IDC_EXPLAINBRIEF                1106
#define IDC_BIGEND1                     1106
#define IDC_BIGMAX1                     1106
#define IDC_MYHELP                      1107
#define IDC_BIGEND2                     1107
#define IDC_BIGMAX2                     1107
#define IDC_STOP                        1108
#define IDC_BIGEND3                     1108
#define IDC_MYHELP2                     1108
#define IDC_BIGMAX3                     1108
#define IDC_EDIT_START                  1109
#define IDC_PASSWORD                    1109
#define IDC_ADDSTOCKTYPE                1109
#define IDC_BIGEND4                     1109
#define IDC_BIGMAX4                     1109
#define IDC_EDIT_END                    1110
#define IDC_BUYINPUT                    1110
#define IDC_SLIDER1                     1110
#define IDC_EDIT_DESTINATION            1111
#define IDC_SELLINPUT                   1111
#define IDC_ADD_STOCKS_PARENT           1111
#define IDC_LIST                        1112
#define IDC_RADIO_FIVEMINUTES           1112
#define IDC_LIST_ADD_STOCKS             1112
#define IDC_SLIDER3                     1112
#define IDC_CHECK7                      1113
#define IDC_SLIDER2                     1113
#define IDC_RADIO_DAY                   1114
#define IDC_GRIDLIST                    1114
#define IDC_TAB2                        1114
#define IDC_EDIT_KEY                    1115
#define IDC_STATIC_TEST_INFO            1115
#define IDC_STATIC_NEIPAN               1116
#define IDC_LIST_CHUQUAN                1117
#define IDC_STATIC_NEIPAN2              1117
#define IDC_CODE                        1117
#define IDC_EDIT_ALARM_NAME             1118
#define IDC_STATIC_NAME                 1119
#define IDC_SETTING_ADDED               1119
#define IDC_CHECK_TIMESPAN              1120
#define IDC_BUY_CASE                    1120
#define IDC_CHECK_FIXTIME               1121
#define IDC_SELL_CASE                   1121
#define IDC_ADD_ITEM                    1122
#define IDC_ADD_STOCK                   1122
#define IDC_EDIT_CQDATE                 1123
#define IDC_EDIT_STOCK                  1123
#define IDC_EDIT_CQGIVE                 1124
#define IDC_IMPORT                      1124
#define IDC_EDIT_CQALLOC                1125
#define IDC_IMPORT2                     1125
#define IDC_EXPORT                      1125
#define IDC_ADD_FORMULA                 1125
#define IDC_EDIT_CQDIVID                1126
#define IDC_MODIFY__FORMULA             1126
#define IDC_EDIT_CQPRICE                1127
#define ID_DELETE_FORMULA               1127
#define IDC_LIST_PROFIT                 1128
#define IDC_MSFLEXGRID5                 1128
#define ID_LIST_FINANCE                 1128
#define IDC_LIST_BARGAIN                1129
#define IDC_STATIC_RESULT_RECORD        1129
#define IDC_LIST_ACCESSFUND             1130
#define IDC_PRINT                       1130
#define IDC_STATIC_TOTALFUND            1131
#define IDC_MYHELP_2                    1131
#define IDC_EDIT_AMOUNT                 1132
#define IDC_COMBO_PERIOD                1132
#define IDC_BUTTON_CAN_USED             1132
#define IDC_EDITDATE                    1133
#define IDC_STATICP1                    1133
#define IDC_CHECK8                      1133
#define IDC_DATETIMEPICKER1             1134
#define IDC_STATICP2                    1134
#define IDC_CHECK9                      1134
#define IDC_EDITSIGN                    1135
#define IDC_STATICP3                    1135
#define IDC_DATETIMEPICKER3             1135
#define IDC_END                         1135
#define IDC_CHECK10                     1135
#define IDC_EDITVOLUME                  1136
#define IDC_STATICP4                    1136
#define IDC_CHECK11                     1136
#define IDC_EDITPRICE                   1137
#define IDC_EDIT_P1                     1137
#define IDC_RADIO_BUY                   1137
#define IDC_EDITFEE                     1138
#define IDC_EDIT_P2                     1138
#define IDC_RADIO_SELL                  1138
#define IDC_USERLIST                    1138
#define IDC_EDITAMOUNT                  1139
#define IDC_EDIT_STOCKCOUNT             1139
#define IDC_EDIT_PRICE                  1139
#define IDC_COMBO                       1139
#define IDC_STATICTOTALCOMMISSION       1140
#define IDC_EDIT_CHOOSECOUNT            1140
#define IDC_EDIT_SYMBOL                 1140
#define IDC_SETTING                     1140
#define IDC_STATICTOTALPROFIT           1141
#define IDC_EDIT_CHOOSEPERCENT          1141
#define IDC_EDIT_SHARES                 1141
#define IDC_CHECK                       1141
#define IDC_STATICTOTALEXTANT           1142
#define IDC_EDIT_TIMESTART              1142
#define IDC_EDIT_VALUE                  1142
#define IDC_VERIFY                      1142
#define IDC_STATICNAME                  1143
#define IDC_LIST_CONDITION              1143
#define IDC_EDIT_FEE                    1143
#define IDC_ADD_ACCOUNT                 1143
#define IDC_EDITSYMBOL                  1144
#define IDC_COMBO_CHOOSEINDEX           1144
#define IDC_EDIT_ACCOUNT                1144
#define IDC_EDITNAME                    1145
#define IDC_STATIC_PRICE                1145
#define IDC_DELETE_ACCOUNT              1145
#define IDC_EDITRATE                    1146
#define IDC_CALCULATOR                  1146
#define IDC_STATIC_SHARES               1146
#define IDC_STATIC_OLD                  1146
#define IDC_COMBOCHECKNUMBER            1147
#define IDC_STATIC_VALUE                1147
#define IDC_DBGRID1                     1147
#define IDC_EDITPASSWORD                1148
#define IDC_STATIC_FEE                  1148
#define IDC_ADD_LOADDATA                1148
#define IDC_EDITNEWCHECK                1149
#define IDC_STATIC_OPM                  1149
#define IDC_STATIC3                     1149
#define IDC_Sta0                        1149
#define IDC_EDITNEWPASSWORD             1150
#define IDC_STATIC_OPE                  1150
#define IDC_Sta1                        1150
#define IDC_EDITCONFIRMPASSWORD         1151
#define IDC_STATIC_ITEM                 1151
#define IDC_Sta2                        1151
#define IDC_PROGRESSYIELD               1152
#define IDC_STATIC_STATISTIC            1152
#define IDC_Sta3                        1152
#define IDC_BUTTON_LEADOUT              1153
#define IDC_Sta4                        1153
#define IDC_BUTTON_LEADIN               1154
#define IDC_Sta5                        1154
#define IDC_RICHEDIT                    1155
#define stocknumcode                    1155
#define IDC_BUTTON_DELETE               1156
#define stocknumname                    1156
#define IDC_clear                       1157
#define IDC_ANIMATEGIFIMAGE1            1158
#define IDC_ADDSTOCK                    1159
#define IDC_RISK_LIST                   1160
#define IDC_DAYS                        1161
#define IDC_RISKINDEX                   1162
#define IDC_SELFDEFINE                  1163
#define IDC_STANAME                     1171
#define IDC_ZDTQ                        1172
#define IDC_LISTCW                      1173
#define IDC_LISTCQ                      1174
#define IDC_TAB_TYPE                    1179
#define IDC_BACKPOWER                   1180
#define IDC_WEEKS                       1182
#define IDC_INTERVAL                    1183
#define IDC_SELDEFINE                   1184
#define IDC_STATIC2                     1185
#define IDC_STATIC11                    1186
#define IDC_COLOR                       1187
#define IDC_STARANGE                    1188
#define IDC_EIGVEC_LIST                 1189
#define IDC_SYMBOL_LIST                 1190
#define IDC_REFRESH_DAY                 1191
#define IDC_DISPLAY_INFO                1192
#define IDC_INFOSAVE                    1193
#define IDC_STATIC_COMPANY              1195
#define IDC_STATIC_USER                 1196
#define IDC_SHOWSTATUS                  1198
#define IDC_SHOWSTA                     1198
#define IDC_ADDRESS                     1199
#define IDC_EDITADDRESS                 1200
#define IDC_COMMONBLOCK1                1201
#define IDC_CJHAND                      1201
#define IDC_COMMONBLOCK2                1202
#define IDC_LTPER                       1202
#define IDC_COMMONBLOCK3                1203
#define IDC_CJJE                        1203
#define IDC_COMMONBLOCK4                1204
#define IDC_WANYUAN                     1204
#define IDC_COMMONBLOCK5                1205
#define IDC_QUEREN                      1205
#define IDC_COMMONBLOCK6                1206
#define IDC_STATIC_PNAME                1206
#define IDC_COMMONBLOCK7                1207
#define IDC_COMMONBLOCK8                1208
#define IDC_TABBAR                      1208
#define IDC_COMMONBLOCK9                1209
#define IDC_STATIC_CAPTION              1209
#define IDC_COMMONBLOCK10               1210
#define IDC_LTP_RATE                    1210
#define IDC_CJL_RATE                    1211
#define IDC_MYXMZLIST                   1212
#define IDC_CHECK_AUTOLOGON             1215
#define IDC_EDIT_SERVER                 1216
#define IDC_EDIT_USERNAME               1217
#define IDC_EDIT_PASSWORD               1218
#define IDC_CHECK_SAVEPASSWORD          1219
#define IDC_COMBO_SERVER                1220
#define IDC_STOCKCODE                   1221
#define IDC_RECV_INFO                   1222
#define IDC_RICHEDIT1                   1223
#define IDC_BUTTON_FRESH                1223
#define IDC_STATIC_COND_NEED            1224
#define IDC_BUTTON_MODIFY               1224
#define IDC_BUTTON_ADD                  1225
#define IDC_BUTTON9                     1225
#define IDC_COMBO_TARGET_PERIOD         1226
#define IDC_BUTTON_FRESH2               1226
#define IDC_BUTTON10                    1226
#define IDC_TAB_SELECT                  1226
#define IDC_BUTTON11                    1227
#define IDC_STATIC_1                    1227
#define IDC_STATIC_COLOR                1227
#define IDC_BUTTON12                    1228
#define IDC_MSCHART1                    1228
#define IDC_MSCHART2                    1229
#define IDC_MSCHART3                    1230
#define IDC_STA_ICON                    1231
#define IDC_EDIT_POWER                  1232
#define IDC_EDIT_DISKID                 1233
#define IDC_EDIT_PERIOD_TARGET_1        2026
#define IDC_EDIT_PERIOD_TARGET          2043
#define IDC_EDIT_PROFIT_T               2044
#define IDB_TOOLBAR_DISABLE             2165
#define ID_AVLINE_ABSCOST               2857
#define ID_AVLINE_BOOLEAN               2858
#define ID_AVLINE_COST                  2859
#define ID_AVLINE_EXPONENT              2860
#define ID_AVLINE_FLOW                  2861
#define ID_AVLINE_MOVE                  2862
#define ID_AVLINE_MULTIEMPTY            2863
#define ID_AVLINE_NULL                  2864
#define ID_AVLINE_SAR                   2865
#define ID_AVLINE_SUNSHINE              2866
#define ID_BLOCKANALYSES                2874
#define ID_CHANNEL                      2884
#define ID_FILE_COPYTOCLIPBOARD         2944
#define ID_FILE_SAVETOBMPFILE           2969
#define ID_FILE_SWITCH                  2971
#define ID_FILE_SYNCMEMORY              2972
#define ID_TOOL_FINANCE                 2973
#define ID_TOOL_INQUERY                 3004
#define ID_MULTICHARTS                  3046
#define ID_MULTIDAYS                    3047
#define ID_MULTIPERIODS                 3048
#define ID_MULTISTOCKS                  3049
#define IDD_DIALOG_INFO                 3205
#define IDC_TREE_INFO                   3206
#define IDD_MANAGER_CHOOSE1             3206
#define IDB_TREEBMP1                    3207
#define IDB_TREEBMP2                    3208
#define IDD_CWD_EXPORT_FORMU            3208
#define IDB_TREEBMP3                    3209
#define IDD_BJ_CHENGBEN_SETTING         3209
#define IDB_STATUSBAR_INDICATOR1        3210
#define IDD_BJ_ADD_DATA                 3210
#define IDB_DRAWICON2                   3211
#define IDB_DRAWICON3                   3212
#define IDB_DRAWICON4                   3213
#define IDB_DRAWICON5                   3214
#define IDS_STOCKNAME                   5910
#define IDS_YSTC                        5911
#define IDS_OPEN                        5912
#define IDS_HIGH                        5913
#define IDS_LOW                         5914
#define IDS_NEW                         5915
#define IDS_TOTV                        5916
#define IDS_NOWV                        5917
#define IDS_TOTP                        5918
#define IDS_AVGP                        5919
#define IDS_ADDE                        5920
#define IDS_HLP                         5921
#define IDS_RDR                         5922
#define IDS_BSSPBAS                     5923
#define IDS_DIFBS                       5924
#define IDS_VOLBI                       5925
#define IDS_ACCB                        5926
#define IDS_ACCS                        5927
#define IDS_BUY                         5928
#define IDS_SEL                         5929
#define IDS_RVOL                        5930
#define IDS_DVOL                        5931
#define IDS_EXCHANGE                    5932
#define IDS_SYL                         5933
#define IDS_ZGB                         5934
#define IDS_GJG                         5935
#define IDS_FQRFRG                      5936
#define IDS_FRG                         5937
#define IDS_ZGG                         5938
#define IDS_GZAG                        5939
#define IDS_LTAG                        5940
#define IDS_HG                          5941
#define IDS_BG                          5942
#define IDS_ZPG                         5943
#define IDS_ZZC                         5944
#define IDS_LDZC                        5945
#define IDS_CQTZ                        5946
#define IDS_GDZC                        5947
#define IDS_WXZC                        5948
#define IDS_LDFZ                        5949
#define IDS_CQFZ                        5950
#define IDS_GGQY                        5951
#define IDS_ZBGJJ                       5952
#define IDS_YYGJJ                       5953
#define IDS_MGJZ                        5954
#define IDS_GDQYBL                      5955
#define IDS_MGGJJ                       5956
#define IDS_ZYYWSR                      5957
#define IDS_ZYYWLR                      5958
#define IDS_QTYWLR                      5959
#define IDS_LRZE                        5960
#define IDS_JLR                         5961
#define IDS_WFPLR                       5962
#define IDS_MGSY                        5963
#define IDS_JZCSYL                      5964
#define IDS_MGWFPLR                     5965
#define IDS_MGJZC                       5966
#define IDS_ZJLS                        5967
#define IDS_VOLBIFM                     5968
#define IDS_HLPFM                       5969
#define IDS_EXCHANGEFM                  5970
#define IDS_ADVSPE                      5971
#define IDS_ADVSP                       5971
#define IDS_UPDOWNS                     5972
#define IDS_UPDOWN                      5972
#define IDS_DELITEM                     5972
#define IDS_EXCHANGEFDS                 5973
#define IDS_HLPFDS                      5974
#define IDS_BFF_TITLE                   5976
#define IDC_COMBO_PERIOD_SELECT         10657
#define ID_TEST                         32772
#define ID_SETTIMEINTER                 32772
#define ID_SETOTHER                     32773
#define ID_BOTTOMPAGEADD                32774
#define ID_SHSTOCKA                     32774
#define ID_SHSTOCKB                     32775
#define ADD_ROW                         32776
#define ID_SHZHSTOCKA                   32776
#define ID_OPEN_STOCK                   32777
#define ID_SHZHSTOCKB                   32777
#define ID_OPEN_DOCUMENT                32778
#define ID_SHZHAIQUAN                   32778
#define ID_ADD_CHOOSE                   32779
#define ID_SHZHZHAIQUAN                 32779
#define ID_ADD_STOCKTYPE                32780
#define ID_DELETE_STOCKTYPE             32781
#define ID_SAVE_SELECT                  32782
#define ID_SAVE_STOCKTYPE               32783
#define ID_STOCK_ASH                    32784
#define ID_STOCKTYPE                    32786
#define ID_FONT_CHANGE                  32787
#define ID_YOU                          32787
#define ID_LINESELF                     32788
#define ID_STOCK_BSH                    32789
#define ID_K_CACL                       32789
#define ID_STOCK_ASZ                    32790
#define ID_VIEW_LINE                    32790
#define ID_STOCK_BSZ                    32791
#define ID_VIEW_SDKJ                    32791
#define ID_XIANDUAN                     32792
#define ID_VIEW_DATAMANAGE              32792
#define ID_VIEW_INVESTMANAGE            32793
#define ID_VIEW_FIFTEENMIN              32793
#define ID_VIEW_COMPANYINFO             32794
#define ID_VIEW_THIRTYMIN               32794
#define ID_VIEW_SIXTYMIN                32795
#define ID_DELETE_FILE                  32795
#define ID_VIEW_DAYLINE                 32796
#define ID_AUTOPAGE                     32796
#define ID_VIEW_WEEKLINE                32797
#define ID_CUOHE_ASH                    32797
#define ID_VIEW_MONUTHLINE              32798
#define ID_CUOHE_BSH                    32798
#define ID_VIEW_ONEITEM                 32799
#define ID_VIEW_TWOITEM                 32800
#define ID_CUOHE_ASZ                    32800
#define ID_BUTTON32801                  32801
#define ID_VIEW_FOURITEM                32801
#define ID_CUOHE_BSZ                    32801
#define ID_ITEM_FOURITEM                32802
#define ID_CUOHE_CHOOSE                 32802
#define ID_VIEW_JSZB                    32803
#define ID_CUOHE_STOCKTYPE              32803
#define ID_VIEW_ZTDJ                    32804
#define ID_FULLSCREEN                   32805
#define ID_VIEW_SIMPLE                  32806
#define ID_VIEW_FOURSTOCK               32807
#define ID_PAGE_SETUP                   32807
#define ID_SHIDUAN_TJ2                  32807
#define ID_VIEW_NINESTOCK               32808
#define ID_CHANGE_DATA                  32809
#define ID_GENERAL_XY                   32810
#define ID_BFB_XY                       32811
#define ID_BASEINFOGRID                 32811
#define ID_BASEINFO_GRID                32811
#define ID_DUISHU_XY                    32812
#define ID_VIEW_BUYSELL                 32813
#define ID_VIEW_FJXX                    32814
#define ID_VIEW_GGXX                    32815
#define ID_COMPANYINFO                  32816
#define ID_VIEW_XX                      32817
#define ID_TJXG_KLINE                   32819
#define ID_TJXG_DELETEKLINE             32820
#define ID_TJXG_ZJTS                    32821
#define ID_TJXG_DELETEZJXT              32822
#define ID_BS_INFO_SHOW                 32822
#define ID_TJXG_ZJXTCS                  32823
#define ID_POWER_DO                     32823
#define ID_CUOHE_OPEN                   32824
#define ID_TJXG_DELETETS                32825
#define ID_TOOL_CURSOR                  32826
#define ID_TOOL_GSGL                    32827
#define ID_TOOL_SJGL                    32828
#define ID_TOOL_ZDWT                    32829
#define ID_TOOL_ZXXT                    32830
#define ID_TOOL_TZGL                    32831
#define ID_HELP_TOPIC                   32832
#define ID_ZHUTU_DIEJIA                 32833
#define ID_REAL_TIME                    32838
#define ID_DAY_LINE                     32839
#define ID_SHIDUAN_TJ                   32840
#define ID_MENUITEM32841                32841
#define ID_VIEW_ONE                     32842
#define ID_VIEW_MONTHLINE               32843
#define ID_VIEW_THREEITEM               32844
#define ID_TOOL_CLOSEWORK               32845
#define ID_STOP_CUOHE                   32846
#define ID_FILE_OPEN1                   32847
#define ID_MENUITEM32848                32848
#define ID_SAVE_TJXG                    32848
#define ID_AUTOCHANGE                   32849
#define ID_VIEWSTOCKDETAIL              32850
#define ID_F2                           32851
#define ID_TOOL_SETTIME                 32852
#define ID_STOCK_BIG                    32852
#define ID_VIEW_YEARKLINE               32853
#define ID_F3                           32857
#define ID_F4                           32858
#define ID_HLDJ_LMB                     32859
#define ID_HEDJ_LMB                     32860
#define ID_MODIFYBOLCKNAME              32861
#define ID_COPY_FILE                    32861
#define ID_DEL_ZHUTU_L                  32862
#define ID_GRID                         32863
#define ID_QLDJ_LMB                     32864
#define ID_QEDJ_LMB                     32865
#define ID_RICH_COPY                    32866
#define ID_KLINE_MANY_DAY               32867
#define ID_NEW_F10                      32867
#define ID_KLINE_1_MINU                 32868
#define ID_KLINE_HS                     32869
#define ID_STOCK_TYPE1                  32869
#define ID_STOCK_TYPE2                  32870
#define ID_STOCK_TYPE3                  32871
#define ID_STOCK_TYPE4                  32872
#define ID_HISTORY_OPEN                 32873
#define IDM_L_SPLIT_V                   32874
#define IDM_L_SPLIT_H                   32875
#define IDM_L_SPLIT_DEL                 32876
#define IDM_L_SPLIT4                    32877
#define ID_HISTORY_GOBACK               32878
#define ID_HISTORY_GOHEAD               32879
#define ID_HISTORY_SWITCH               32880
#define ID_HISTORY_HIDE                 32881
#define ID_HISTORY_CLOSE                32882
#define ID_HISTORY_A_STEP               32883
#define ID_CLASSIFY_JISHU               32884
#define ID_PAGE_GO_BACK                 32885
#define ID_PAGE_GO_AHEAD                32886
#define ID_TO_GRID                      32887
#define ID_TJXG_ALARM                   32888
#define IDD_TOTP                        32890
#define IDD_HLP                         32891
#define IDD_RDR                         32892
#define IDD_BSSPBAS                     32893
#define IDD_VOLBI                       32894
#define ID_LOOP_DISPLAY                 32895
#define IDD_DVOL                        32895
#define IDD_EXCHANGE                    32896
#define IDD_SYL                         32897
#define IDD_ZJLS                        32898
#define IDD_HLPFM                       32899
#define IDD_EXCHANGEFM                  32900
#define IDD_ADVSP                       32901
#define ID_DRAWLINE_COLOR               32902
#define ID_DRAWLINE_SOLIDLINE           32903
#define ID_DRAWLINE_VIRTUALLINE         32904
#define ID_DRAWLINE_DOTLINE             32905
#define ID_DRAWLINE_LINEWID1            32906
#define ID_DRAAWLINE_LINEWID2           32907
#define ID_DRAAWLINE_LINEWID3           32908
#define ID_JISHU_EXPLAIN                32909
#define ID_MODIFY_JISHU_POP             32910
#define ID_TREND_LINE_ALARM             32912
#define ID_MOVE_CHENGBEN_2              32917
#define ID_TJXG_MM_TEST                 32918
#define ID_TJXG_MM_TEST_SHOW            32919
#define ID_TOOL_NNET_TRAIN              32920
#define ID_TIME_ASTEP_4                 32922
#define ID_TOOL_BLOCK_MANA              32923
#define ID_DOWNLOAD_20                  32924
#define ID_CLOSE_RECEIVER               32925
#define ID_FILE_OUT_DATA                32926
#define ID_STOCK_ANALYSIS               32928
#define ID_RISKINDEX                    32928
#define ID_NINE_SHOW                    32929
#define ID_SYNC                         32930
#define ID_MENU_TYPE1                   32931
#define ID_VIEW_FIVEITEM                32931
#define ID_MENU_TYPE2                   32932
#define ID_MENU_TYPE3                   32933
#define ID_MENU_TYPE4                   32934
#define ID_MENU_TYPE5                   32935
#define ID_SPIRE_LINE                   32937
#define ID_SZEB                         32938
#define ID_MENUITEM_DELETE_K            32939
#define ID_TJXG                         32941
#define ID_CLOSE                        32942
#define ID_HIST_OPEN_POP                32943
#define ID_ADD_TO_SELF                  32944
#define IDM_TONGJI_Index_               32946
#define ID_PARAM_YH                     32947
#define ID_MENU_TEST_HQ                 32950
#define ID_LOGIN_SERVER                 32951
#define ID_RECV_STOCKCODE               32952
#define ID_TIMESHARING                  32953
#define ID_MOVE_FIGUER                  32954
#define IDM_SORT_INDEX                  32955
#define ID_SAVE_BITM                    32956
#define ID_XGN_EXT_DATA                 32957
#define ID_CLEAR_REALDATA               32958
#define ID_GDFX_BANKER                  32960
#define ID_GDFX_EXTSEAT                 32961
#define ID_GDFX_FUND_IN_STK             32962
#define ID_GDFX_EXG_SEARCH              32963
#define ID_GDFX_FUND_FAMILY             32964
#define ID_GDFX_BANKER_INVERT           32965
#define ID_GDFX_EXGSEAT_SEARCH          32966
#define ID_GDFX_FUND_TEN                32967
#define ID_GDFX_FUND_INVERT             32968
#define ID_GDFX_INTELLIGENCE_SELECT     32969
#define ID_DELETE_ADDED_INDICATOR       32970
#define ID_SWITCH_HISTORY_ACC           32971
#define ID_CALC                         32972
#define ID_SWITCH_FINANCE               32973
#define ID_MENUITEM32975                32975
#define IDM_GDFX_REGISTE                32976
#define ID_MENUITEM32977                32977
#define IDM_TOOL_DRAWLINE               42786
#define IDM_DRAWLINE                    42786
#define ID_MENU_1FS                     42790
#define ID_DAY_KLINE                    42791
#define ID_VIEW_FIVEMIN                 42792
#define ID_VIEW_5MIN                    42792
#define ID_L_FENSHI                     42795
#define ID_L_CHENG_JIAO_L               42796
#define ID_L_MMLD                       42797
#define ID_L_LB                         42798
#define ID_L_LINGXIAN                   42799
#define ID_L_DUOKONG                    42800
#define ID_L_TENGLUO                    42801
#define ID_EXTEND_KLINE                 42806
#define ID_NOMALSCREEN                  42806
#define ID_RESTORE_KLINE                42808
#define ID_VIEW_PERSENT                 42809
#define ID_VIEW_DSZB                    42810
#define ID_VIEW_GPHQ                    42812
#define ID_KLINE_5                      42813
#define ID_KLINE_15                     42814
#define ID_KLINE_30                     42815
#define ID_KLINE_60                     42816
#define ID_KLINE_ZHOU                   42817
#define ID_TJXG_TJXG                    42818
#define ID_KLINE_YUE                    42818
#define ID_KLINE_NIAN                   42819
#define IDM_KLINE_MD                    42821
#define ID_TJXG_TJXGTS                  42824
#define ID_KLINE_ZHOU2                  42838
#define ID_KLINE_YUE2                   42839
#define ID_CHANGETYPE                   52797
#define AFX_IDS_APP_TITLE2              57346
#define AFX_IDS_IDLEMESSAGE2            57347
#define ID_FILE_NEW2                    57608
#define ID_FILE_OPEN2                   57610
#define ID_FILE_CLOSE2                  57611
#define ID_FILE_SAVE2                   57612
#define ID_FILE_SAVE_AS2                57613
#define ID_FILE_PAGE_SETUP2             57614
#define ID_FILE_PRINT_SETUP2            57615
#define ID_FILE_PRINT2                  57638
#define ID_FILE_PRINT_PREVIEW2          57639
#define ID_FILE_MRU_FILE17              57645
#define ID_FILE_MRU_FILE18              57646
#define ID_FILE_MRU_FILE19              57647
#define ID_FILE_MRU_FILE20              57654
#define ID_FILE_MRU_FILE21              57655
#define ID_FILE_MRU_FILE22              57656
#define ID_FILE_MRU_FILE23              57657
#define ID_FILE_MRU_FILE24              57658
#define ID_FILE_MRU_FILE25              57659
#define ID_FILE_MRU_FILE26              57660
#define ID_FILE_MRU_FILE27              57661
#define ID_FILE_MRU_FILE28              57662
#define ID_FILE_MRU_FILE29              57663
#define ID_FILE_MRU_FILE30              57666
#define ID_FILE_MRU_FILE31              57667
#define ID_FILE_MRU_FILE32              57668
#define ID_EDIT_CLEAR2                  57669
#define ID_EDIT_CLEAR_ALL2              57670
#define ID_EDIT_COPY2                   57671
#define ID_EDIT_CUT2                    57672
#define ID_EDIT_FIND2                   57673
#define ID_EDIT_PASTE2                  57674
#define ID_EDIT_REPEAT2                 57675
#define ID_EDIT_REPLACE2                57676
#define ID_EDIT_SELECT_ALL2             57677
#define ID_EDIT_UNDO2                   57678
#define ID_EDIT_REDO2                   57679
#define ID_WINDOW_NEW2                  57682
#define ID_WINDOW_ARRANGE2              57683
#define ID_WINDOW_CASCADE2              57684
#define ID_WINDOW_TILE_HORZ2            57685
#define ID_WINDOW_TILE_VERT2            57686
#define ID_WINDOW_SPLIT2                57687
#define ID_APP_ABOUT2                   57688
#define ID_APP_EXIT2                    57689
#define ID_NEXT_PANE2                   57690
#define ID_PREV_PANE2                   57691
#define ID_INDICATOR_EXT2               59142
#define ID_INDICATOR_CAPS2              59143
#define ID_INDICATOR_NUM2               59144
#define ID_INDICATOR_SCRL2              59145
#define ID_INDICATOR_OVR2               59146
#define ID_INDICATOR_REC2               59147
#define ID_VIEW_TOOLBAR2                59394
#define ID_VIEW_STATUS_BAR2             59395
#define AFX_IDS_SCSIZE2                 61191
#define AFX_IDS_SCMOVE2                 61192
#define AFX_IDS_SCMINIMIZE2             61193
#define AFX_IDS_SCMAXIMIZE2             61194
#define AFX_IDS_SCNEXTWINDOW2           61195
#define AFX_IDS_SCPREVWINDOW2           61196
#define AFX_IDS_SCCLOSE2                61197
#define AFX_IDS_SCRESTORE2              61204
#define AFX_IDS_SCTASKLIST2             61205
#define AFX_IDS_MDICHILD2               61216
#define AFX_IDS_PREVIEW_CLOSE2          61446
#define IDS_LOGON                       61453

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        448
#define _APS_NEXT_COMMAND_VALUE         32978
#define _APS_NEXT_CONTROL_VALUE         1234
#define _APS_NEXT_SYMED_VALUE           215
#endif
#endif
