#include ChildFrm.h
#include MainFrm.h
#include mainFrmD.h
#include Resource.h
#include SHEET1.h
#include SHEET2.h
#include SHEET3.h
#include SHEET4.h
#include Sheet5.h
#include SHEETC.h
#include Stdafx.h
#include vwbase.h
//#include vwbaseDoc.h
#include "CTaiShanDoc.h"
#include CTaiShanKlineShowView.h
