#if !defined(AFX_ROWCURSOR_H__7EE27666_D065_11D1_83F0_0000E8593F1A__INCLUDED_)
#define AFX_ROWCURSOR_H__7EE27666_D065_11D1_83F0_0000E8593F1A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


class CRowCursor : public COleDispatchDriver
{
public:
	CRowCursor() {}		
	CRowCursor(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CRowCursor(const CRowCursor& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}


public:


public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ROWCURSOR_H__7EE27666_D065_11D1_83F0_0000E8593F1A__INCLUDED_)
